// ================================================================
// clinical.d.ts — ClinicalEngine structured type contracts
// Phase 20: Type Governance Foundations
//
// Documents the normalized clinical model, case classification,
// treatment option shapes, and process() / processCompound() outputs.
// ================================================================

// ── Case type constants (mirrors ClinicalEngine.CT) ───────────
type CaseType =
  | 'MISSING_SINGLE'
  | 'MISSING_MULTI'
  | 'RESTORATIVE_VIABLE'
  | 'RESTORATIVE_COMPROMISED'
  | 'RESTORATIVE_HOPELESS';

interface CaseClass {
  type: CaseType;
  label: string;
  notes?: string;
}

// ── Treatment options generated by generateTreatments() ───────
interface TreatmentOption {
  slot: TxSlot;
  id: 'onlay' | 'endocrown' | 'crown_core' | 'crown' | 'splinted' | 'crown_adv' | 'extract_impl';
  label: string;
  sub: string;
}

interface ScoredTreatment extends TreatmentOption {
  score: number;
  rationale: string[];
}

// ── Explanation summary from explain() ────────────────────────
interface ExplanationSummary {
  summary: string;
  reasons: string[];
  factors: AIFactor[];
  recOption: ScoredTreatment;
}

// ── Restorative slot labels for aiCardPanel + report templates ─
interface TreatmentSlotLabels {
  slot1: TreatmentOption;
  slot2: TreatmentOption;
  slot3: TreatmentOption;
}

// ── Normalized clinical model from ClinicalEngine.normalize() ─
interface NormalizedClinical {
  tooth: {
    id: string; isMaxilla: boolean; isPosterior: boolean;
    isAnterior: boolean; isMandibular: boolean;
  };
  restorative: {
    condition: string; remainingStructure: string; endoStatus: string;
    isMissing: boolean; hasFracture: boolean; hasDecay: boolean;
    hasFailedResto: boolean; needsRCT: boolean; rctDone: boolean;
    goodStructure: boolean; fairStructure: boolean; poorStructure: boolean;
  };
  periodontal: {
    bone: string; hygiene: string;
    goodBone: boolean; fairBone: boolean; poorBone: boolean;
    goodHygiene: boolean; poorHygiene: boolean;
  };
  occlusal: {
    load: string; highLoad: boolean;
    parafunction: string; bruxism: boolean; clenching: boolean;
  };
  systemic: {
    smoking: string; diabetes: string;
    currentSmoker: boolean; uncontrolledDM: boolean;
  };
  biomechanical: {
    ferrule: string; goodFerrule: boolean; poorFerrule: boolean;
    abutmentQuality: string; abutmentCompromised: boolean;
  };
  patient: { age: number; young: boolean; elderly: boolean };
  multi: { active: boolean; tooth2: string | undefined };
  costs: { implant: number; crown: number; rct: number; postCore: number };
}

// ── ClinicalEngine.process() return types ─────────────────────

// Restorative path — full structured 7-stage pipeline result
interface ClinicalAIResult extends CalcAIResult {
  treatmentMode: 'restorative';
  caseClass: CaseClass;
  clinical: NormalizedClinical;
  treatments: TreatmentOption[];
  scored: ScoredTreatment[];
  explanation: ExplanationSummary;
  restorativeLabels: TreatmentSlotLabels;
  recDisplay: string;
  restorativeCosts: { slot1: number; slot2: number; slot3: number };
}

// MISSING_SINGLE path — delegates to calcAI()
type SingleMissingResult = CalcAIResult & {
  treatmentMode: 'single';
  caseClass: CaseClass;
  clinical: NormalizedClinical;
};

// MISSING_MULTI path — delegates to calcAIMulti()
type MultiMissingResult = CalcAIMultiResult & {
  treatmentMode: 'multi';
  caseClass: CaseClass;
  clinical: NormalizedClinical;
};

// Union of all possible ClinicalEngine.process() return shapes
type ProcessResult = ClinicalAIResult | SingleMissingResult | MultiMissingResult;

// ── ClinicalEngine.processCompound() return type ──────────────
interface CompoundAIResult {
  isCompound: true;
  site1: ProcessResult | null;
  site2: ProcessResult | null;
  site1Tooth: string;
  site2Tooth: string;
  site1Condition: string;
  site2Condition: string;
}
